baseURL = 'www.peterp.dev'
languageCode = 'en-us'
title = 'Peter Piontek'
themesDir = 'themes'
publishDir = 'docs'
theme = "m10c"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "recipes"
    name = "Recipes"
    url = "/recipes/"
    weight = 2
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 4

[params]
  author = "Peter Piontek"
  description = "hi there"
  menu_item_separator = " - "
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/ppiont"
  [[params.social]]
    icon = "gitlab"
    name = "GitLab"
    url = "https://gitlab.com/ppiont"

